server:
  port: ${PORT:8081}
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
      discovery:
        enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: https://eureka-service-ms.herokuapp.com/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true